### ISSUE TITLE
SendFileAsync

### ISSUE THREAD

**Issue by diagtruck** [idan-rubin/icq.bot.net#1]
I tried to use this method:
                        using (var st = File.Open(f, FileMode.Open))
                        {
                            InputOnlineFile inputFiles1 = new InputOnlineFile(st,f);
                            bot.SendFileAsync(message.From.UserId, inputFiles1).Wait();
};
Method doen't work. Can you explain, how it works.

**Comment by idan-rubin** [comment]
Thank you @diagtruck! You are correct that SendFileAsync is broken - working on the fix for that.

**Comment by diagtruck** [comment]
Some types of messages stoped all events. 



Отправлено из мобильной Почты Mail.ru


пятница, 1 мая 2020 г., 15:13 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by idan-rubin** [comment]
Version 1.0.8 has a fix for sending file streams. Thank you again for reporting it.

Do you have example for a type of message that stopped all events?

**Comment by diagtruck** [comment]
Can I help you.  Test  or another. 



Отправлено из мобильной Почты Mail.ru


пятница, 1 мая 2020 г., 20:19 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by idan-rubin** [comment]
You can definitely help me with this project!
* Help with testing and opening issues for bugs or suggestions
* Help spread the word and make icq.bot.net more popular
* Become a contributor and help add unit tests and new features to the project

Thanks,
Idan

**Comment by idan-rubin** [comment]
@diagtruck - are you able to send a file stream with version 1.0.8? If so, I'll close this issue.

Thanks,
Idan

**Comment by diagtruck** [comment]
I’ll try it tomorrow morning. 
Please explain callback in messages. How to. I tryed  but  i could not use it. 



Отправлено из мобильной Почты Mail.ru


вторник, 5 мая 2020 г., 21:30 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by diagtruck** [comment]
bot.SendFileAsync(SenderID, new ICQ.Bot.Types.InputFiles.InputOnlineFile(ss), "Screen");
 
does not work. Where ss MemoryStream.

**Comment by idan-rubin** [comment]
@diagtruck - I will investigate today the failure in sending a memory stream. Thank you for reporting this.

Regarding your problem with messages callback - I opened a new issue for that (https://github.com/idan-rubin/icq.bot.net/issues/2)
1. Did you try running the example from the README file?
2. Can you share your code that doesn't work with me?

**Comment by idan-rubin** [comment]
@diagtruck - Version 1.1.0 has a fix for sending a file as memory stream.

**Comment by idan-rubin** [comment]
All issues should be resolved with version 1.2 :)
