### ISSUE TITLE
bot.AnswerCallbackQueryAsync(e.QueryId).Wait();

### ISSUE THREAD

**Issue by diagtruck** [idan-rubin/icq.bot.net#4]
System.AggregateException
  HResult=0x80131500
  Сообщение = One or more errors occurred. (Object reference not set to an instance of an object.)
NullReferenceException: Object reference not set to an instance of an object.

**Comment by idan-rubin** [comment]
Thank you for reporting this. Version 1.3.1 has a fix for the issue.

**Comment by idan-rubin** [comment]
Version 1.4 has a fix for this. Thanks.
