### ISSUE TITLE
 bot.DeleteMessagesAsync

### ISSUE THREAD

**Issue by diagtruck** [idan-rubin/icq.bot.net#5]
Type of messageIds are not **Int**. Long or string maybe.

**Comment by idan-rubin** [comment]
version 1.4 has a fix for this. Thanks!

**Comment by idan-rubin** [comment]
Note that in the documentation, mgsId is an int - https://icq.com/botapi/#/messages/get_messages_deleteMessages

**Comment by diagtruck** [comment]
Int 32 and int64 different things. 



Отправлено из мобильной Почты Mail.ru


воскресенье, 17 мая 2020 г., 18:27 +0300 от notifications@github.com  <notifications@github.com>:
