### ISSUE TITLE
I get old callbacks everytime when i start project

### ISSUE THREAD

**Issue by diagtruck** [idan-rubin/icq.bot.net#6]

**Comment by idan-rubin** [comment]
@diagtruck - can you please share your code with me?

**Comment by idan-rubin** [comment]
This might be related to callback events that happened between client runs (client was down during this time)

**Comment by diagtruck** [comment]
Yes. Tomorrow. 



Отправлено из мобильной Почты Mail.ru


воскресенье, 17 мая 2020 г., 18:21 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by diagtruck** [comment]
Get message with lastmessage property. 



Отправлено из мобильной Почты Mail.ru


воскресенье, 17 мая 2020 г., 18:36 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by diagtruck** [comment]
Use Get message with lastmessage property. 



Отправлено из мобильной Почты Mail.ru


воскресенье, 17 мая 2020 г., 18:36 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by idan-rubin** [comment]
the library updates the lastEventId parameter in /events/get API. However, events that happened after the bot was down will show up in the next run...

**Comment by diagtruck** [comment]
Situation.
User pressed callback button when bot application was not started.
When i start application, i receive callback events from buttons and answer
 bot.AnswerCallbackQueryAsync(e.QueryId).Wait();
 but after restart application i receive same events again.

**Comment by diagtruck** [comment]
> @diagtruck - can you please share your code with me?

        private static void BotOnCallBackQuery(object sender, CallbackQueryEventArgs e)
        {
            var mText = e.CallbackData;
            bot.AnswerCallbackQueryAsync(e.QueryId).Wait();
            bot.DeleteMessageAsync (e.From.UserId, new List<long>() { e.Message.MsgId }).Wait();

**Comment by idan-rubin** [comment]
Hello @diagtruck, I tried the situation you describe above, but could not reproduce your problem. Please review the code at https://github.com/idan-rubin/icq.bot.net/blob/master/ICQ.Bot/ICQBotClient.cs in line 212, which calculate the new "lastEventId" parameter for the /events/get API.

When you first start the bot it will send "lastEventId=0" and will get all events from last session, but the next request will have the correct eventId which should make ICQ not resent events.

**Comment by diagtruck** [comment]
May be it was mail.ru  problem with callbacks. I’ll check. 

С уважением,
                           Сергей Белянин. 

среда, 20 мая 2020 г., 18:31 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by idan-rubin** [comment]
Here is an example of the flow you describe using Fiddler:
![image](https://user-images.githubusercontent.com/4691359/82636512-79304000-9c0b-11ea-908e-cce75db5bee1.png)
This is the scenario above:
1. Make sure bot is not running
2. Click a button with callback
3. Run the bot
4. Stop the bot (end the process)
5. Run the bot again

There are 3 calls to /events/get/ (highlighted) - this is the API that gets all of the bots events:
First and second call happen in step 3. You can see that the first call has lastEventId=0 and the second call has lastEventId=120.

The third call is in step 5, and you can see the lastEventId=0 and the response has no events.

**Comment by idan-rubin** [comment]
@diagtruck - did you manage to reproduce this issue?
