### ISSUE TITLE
Support for text formatting

### ISSUE THREAD

**Issue by RangerRU** [idan-rubin/icq.bot.net#7]
Please add support for text formatting https://github.com/mail-ru-im/bot-golang/commit/4fca30eb43976beb4d6b1dbf11bbfcbcc5fe87b1 [Supporting MarkdownV2 and HTML parse modes]

https://icq.com/botapi/tutorial/

**Comment by idan-rubin** [comment]
@RangerRU - great suggestion! Would you like to contribute to the project?

**Comment by RangerRU** [comment]
Unfortunately my knowledge is not enough for this ((((

**Comment by idan-rubin** [comment]
fyi @RangerRU - there is support for MarkdownV2 and HTML text formatting in version [1.4.7](https://www.nuget.org/packages/ICQ.Bot/1.4.7), however it doesn't seem to work yet. I'm consulting with ICQ's tech group.
