### ISSUE TITLE
Constantly generates falls positive BotOnReceiveError Events

### ISSUE THREAD

**Issue by MayMih** [idan-rubin/icq.bot.net#8]
Is seems like after some time when bot is doing nothing (probably after standard dotNet HttpClient.Timeout) it begans to periodically generate BotOnReceiveError Events.
I suppose it is falls positive, cause bot logic continues to work ok.

Steps to reproduce:
Start any bot (e.g. https://github.com/idan-rubin/ICQTranslatorBot) with BotOnReceiveError handler attached and look for its results.

For ICQTraslatorBot it looks like:
```
Start listening for @...
Received error: 408 - request timed out
Received error: 408 - request timed out
<...>
Received error: 408 - request timed out
```

**Comment by idan-rubin** [comment]
https://github.com/idan-rubin/icq.bot.net/pull/14
